Repository microsoft/needlr, pull requests merged in 2025-01, with the labels that each got.

#53 Add pyproject TOML and README to needlr package
  needlr/README.md
  needlr/pyproject.toml
Labels: bug

#68 Fix access to dev dependencies in pyproject.toml
  pyproject.toml
Labels: bug

#71 Initial Config JS and GW
  needlr/core/gateway/gateway.py
  needlr/core/jobscheduler/jobscheduler.py
  needlr/core/workspace/workspace.py
  needlr/models/gateway.py
  needlr/models/jobscheduler.py
  tests/core/test_workspace_job_scheduler.py
Labels: enhancement

#72 Add pytest ini config
  pyproject.toml
Labels: bug, enhancement
